name: senior_mhealth_mobile
description: "Your Project Name - Mobile Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.7.0
  firebase_storage: ^12.4.10
  cloud_firestore: ^5.6.12
  firebase_messaging: ^15.2.10
  permission_handler: ^11.1.0
  connectivity_plus: ^5.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  flutter_dotenv: ^5.1.0
  logging: ^1.2.0
  device_info_plus: ^10.1.0
  path_provider: ^2.1.5
  flutter_background: ^1.2.0
  flutter_local_notifications: ^18.0.1
  uuid: ^4.5.1
  cloud_functions: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env